name: devpack-for-rust
title: Devpack for Rust
license: GPL-3.0
version: "0.1.0"
summary: Zero to Rust development in seconds.
description: |
  An install wizard for batteries-included Rust development. Pick your version of rustc,
  your IDE, and your favorite oxidized tools, and let the tool do the rest.
base: core26
# Requires access to apt and snap
confinement: classic
source-code: https://github.com/canonical/devpack-for-rust
website: https://github.com/canonical/devpack-for-rust
contact: petrichor.park@canonical.com
issues: https://github.com/canonical/devpack-for-rust/issues

parts:
  devpack-for-rust:
    plugin: rust
    source: .

apps:
  devpack-for-rust:
    command: bin/devpack-for-rust
